kind: pipeline
name: default
steps:
- name: psr-check
  build:
    context: ./
    dockerfile: app.dockerfile
  commands:
  - >
    phpcs -d memory_limit=500M --standard=./phpcs.xml --ignore=/vendor/ ./code/
- name: sonarqube
  image: sonarsource/sonar-scanner-cli
  commands:
  - >
    sonar-scanner
    -Dsonar.host.url=http://sonar.scuti.asia
    -Dsonar.login=0b13c64dce2be4f63f16100d6a37126006a17ec6
    -Dsonar.projectKey=${DRONE_REPO_OWNER}:${DRONE_REPO_NAME}
    -Dsonar.projectName=${DRONE_REPO_OWNER}:${DRONE_REPO_NAME}
    -Dsonar.projectVersion=${DRONE_TAG}
    -Dsonar.projectBaseDir=./code/
    -Dsonar.sourceEncoding=UTF-8
    -Dsonar.buildbreaker.skip=false
    -Dsonar.qualitygate.wait=true
