kind: pipeline
name: default
steps:
- name: code-analysis
  image: sonarsource/sonar-scanner-cli
  commands:
  - >
    sonar-scanner
    -Dsonar.host.url=http://sonar.scuti.asia
    -Dsonar.login=81c92b639c333b705827802bbc2ef94206ae6a8d
    -Dsonar.projectKey=${DRONE_REPO_OWNER}:${DRONE_REPO_NAME}
    -Dsonar.projectName=${DRONE_REPO_OWNER}:${DRONE_REPO_NAME}
    -Dsonar.projectVersion=${DRONE_TAG}
    -Dsonar.projectBaseDir=.
    -Dsonar.sourceEncoding=UTF-8
