kind: pipeline
name: default
steps:
- name: psr-check
  image: php:7.1.5-alpine
  commands:
  - >
    curl -L https://github.com/squizlabs/PHP_CodeSniffer/releases/download/3.3.2/phpcs.phar > /usr/local/bin/phpcs \
    && chmod +x /usr/local/bin/phpcs \
    && rm -rf /var/cache/apk/* /var/tmp/* /tmp/* \
    && phpcs -d memory_limit=500M --standard=./phpcs.xml --ignore=/vendor/ ./code/
- name: sonarqube
  image: sonarsource/sonar-scanner-cli
  commands:
  - >
    sonar-scanner
    -Dsonar.host.url=http://sonar.scuti.asia
    -Dsonar.login=0b13c64dce2be4f63f16100d6a37126006a17ec6
    -Dsonar.projectKey=${DRONE_REPO_OWNER}:${DRONE_REPO_NAME}
    -Dsonar.projectName=${DRONE_REPO_OWNER}:${DRONE_REPO_NAME}
    -Dsonar.projectVersion=${DRONE_TAG}
    -Dsonar.projectBaseDir=./code/
    -Dsonar.sourceEncoding=UTF-8
    -Dsonar.buildbreaker.skip=false
    -Dsonar.qualitygate.wait=true
